#! /bin/sh



# load tty keymap if in tty
tty | grep -q tty && doas loadkeys ~/.config/keyboard/tty.kmap

ghc () {
	
	mkdir -p "/src/github.com/$1"
	git -C "/src/github.com/$1" clone "https://www.github.com/$1/$2.git"
}

