#! /bin/sh
XNOTIFY_FIFO="$HOME/.cache/xnotify$DISPLAY.fifo"
export XNOTIFY_FIFO
rm -f $XNOTIFY_FIFO
mkfifo $XNOTIFY_FIFO
xnotify <$XNOTIFY_FIFO 3<>$XNOTIFY_FIFO &

jqs='if .app_icon != "" then "IMG:" + .app_icon + "\t" else "" end
+ .summary + "\t" + .body'

tiramisu -j | jq --raw-output --unbuffered "$jqs" > $XNOTIFY_FIFO &
