#! /bin/sh

export XINIT_LOG="$XDG_CACHE_HOME/xorg/xinit.log"
mkdir -p "$(dirname "$XINIT_LOG")"
echo "xinit: " > "$XINIT_LOG"


for script in $(find "$XINITRC.d/" -type f -executable | sort )
do
	. "$script" # >"$XINIT_LOG" 2>&1
done

# mons -p eDP-1-1 -o
# setxkbmap se us caps:escape
# xsetroot -cursor_name left_ptr

# xinput set-prop 15 341 1

# run-parts --regex '^.*$' "$XINITRC.d" -v >> "$XINIT_LOG"
# Window manager
#exec xmonad
